repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.5.6
    hooks:
      - id: ruff-format
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
      - id: mypy
        additional_dependencies: []
        args: ["--show-error-codes"]

  - repo: local
    hooks:
      - id: lizard
        name: lizard
        entry: lizard
        language: python
        additional_dependencies: ["lizard==1.17.10"]
        types: [python]
        args:
          [
            "-x",
            "src/gera_coordenadas.egg-info/*",
            "--verbose",
            "--warnings_only",
          ]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: python -m pytest
        language: system
        args:
          [
            "tests",
            "--tb=short",
            "--strict-markers",
            "-v",
            "--cov=.",
            "--cov-report=xml",
          ]
        pass_filenames: false
        always_run: true
